FROM node:18 as build

WORKDIR /app

COPY /code/js/package*.json ./

RUN npm install

COPY /code/js ./

RUN npm run build

FROM nginx

COPY /dockerfiles/nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8000